use crate::AppEvent;
use chrono::{DateTime, Utc};
use ratatui::widgets::ListState;
use ratatui_textarea::TextArea;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::collections::HashMap;
use std::marker::PhantomData;
use stormchaser_model::workflow::RunStatus;
use stormchaser_model::ConnectionId;
use stormchaser_model::CronWorkflowId;
use stormchaser_model::RuleId;
use stormchaser_model::RunId;
use stormchaser_model::StepInstanceId;
use stormchaser_model::WebhookId;
use tokio::sync::mpsc;

use stormchaser_model::connections;
use stormchaser_model::cron;
use stormchaser_model::event_rules;
use stormchaser_model::test_report;

/// A summary of a workflow run, used for list views.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct WorkflowRunDetail {
    /// Unique identifier for the run.
    pub id: RunId,
    /// Name of the workflow.
    pub workflow_name: String,
    /// The user who initiated the run.
    pub initiating_user: String,
    /// The current status of the run.
    pub status: RunStatus,
    /// The time the run was created.
    pub created_at: DateTime<Utc>,
    /// The time the run finished, if it has completed.
    pub finished_at: Option<DateTime<Utc>>,
}

/// Detailed information about a single step within a workflow run.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct StepDetail {
    /// The step instance data.
    pub instance: Value,
    /// The outputs produced by the step.
    pub outputs: Vec<Value>,
    /// The execution history of the step.
    pub history: Vec<Value>,
    /// The logs generated by the step.
    pub logs: Vec<String>,
}

/// Comprehensive details of a workflow run, including its steps and artifacts.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct WorkflowRunFullDetail {
    /// The summary details of the run.
    pub detail: WorkflowRunDetail,
    /// The detailed information for each step in the run.
    pub steps: Vec<StepDetail>,
    /// Artifacts generated during the run.
    pub artifacts: Vec<connections::ArtifactRegistry>,
    /// Test summaries generated during the run.
    pub test_summaries: Vec<test_report::TestSummary>,
    /// Individual test cases executed during the run.
    pub test_cases: Vec<test_report::TestCase>,
}

/// Request payload for exchanging an SSO token for access tokens.
#[derive(Debug, Serialize, Deserialize)]
pub struct AuthExchangeRequest {
    /// The single sign-on token to exchange.
    pub sso_token: String,
    /// The callback URL used during the OAuth flow.
    pub callback_url: String,
}

/// Response payload containing access and refresh tokens after successful authentication.
#[derive(Debug, Serialize, Deserialize)]
pub struct AuthExchangeResponse {
    /// The access token for authenticating API requests.
    pub access_token: String,
    /// An optional token used to refresh the access token.
    pub refresh_token: Option<String>,
}

/// Represents the current authentication state of the application.
#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub enum AppState {
    /// The user is not currently logged in.
    LoggedOut,
    /// A login attempt is currently in progress.
    LoggingIn,
    /// The user is successfully logged in.
    LoggedIn,
}

/// Represents the currently active pane in the user interface.
#[derive(Debug, PartialEq, Eq, Clone, Copy)]
pub enum Pane {
    /// The pane displaying the list of workflow runs.
    RunsList,
    /// The pane displaying detailed information for a selected run.
    RunDetail,
    /// The pane displaying test results for a selected run.
    TestResults,
    /// The pane displaying the list of storage backends.
    ConnectionsList,
    /// The pane displaying detailed information for a selected storage backend.
    ConnectionDetail,
    /// The pane displaying the list of webhooks.
    WebhooksList,
    /// The pane displaying detailed information for a selected webhook.
    WebhookDetail,
    /// The pane displaying the list of event rules.
    EventRulesList,
    /// The pane displaying detailed information for a selected event rule.
    EventRuleDetail,
    /// The pane displaying the list of cron workflows.
    CronWorkflowsList,
    /// The pane displaying detailed information for a selected cron workflow.
    CronWorkflowDetail,
}

/// The main application state holding all data and UI status for the TUI.
pub struct App<'a> {
    /// The base URL of the Stormchaser API.
    pub url: String,
    /// The base URL of the Stormchaser Query API.
    pub query_url: String,
    /// The current authentication state.
    pub state: AppState,
    /// The current access token, if logged in.
    pub token: Option<String>,
    /// The current refresh token, if available.
    pub refresh_token: Option<String>,
    /// Filter for run owner.
    pub filter_owner: Option<String>,
    /// Filter for run name.
    pub filter_name: Option<String>,
    /// Filter for repository URL.
    pub filter_repo_url: Option<String>,
    /// Filter for workflow path.
    pub filter_workflow_path: Option<String>,
    /// Filter for created after date.
    pub filter_created_after: Option<String>,
    /// Filter for created before date.
    pub filter_created_before: Option<String>,
    /// Filter for run status.
    pub filter_status: Option<String>,
    /// The current list of loaded workflow runs.
    pub runs: Vec<WorkflowRunDetail>,
    /// The state of the runs list widget (selected item, scroll offset).
    pub runs_state: ListState,
    /// The full details of the currently selected run, if any.
    pub selected_run: Option<WorkflowRunFullDetail>,
    /// The current list of storage backends.
    pub connections: Vec<connections::Connection>,
    /// The state of the storage backends list widget.
    pub connections_state: ListState,
    /// The currently selected storage backend.
    pub selected_connection: Option<connections::Connection>,
    /// The current list of webhooks.
    pub webhooks: Vec<event_rules::WebhookConfig>,
    /// The state of the webhooks list widget.
    pub webhooks_state: ListState,
    /// The currently selected webhook.
    pub selected_webhook: Option<event_rules::WebhookConfig>,
    /// The current list of event rules.
    pub event_rules: Vec<event_rules::EventRule>,
    /// The state of the event rules list widget.
    pub event_rules_state: ListState,
    /// The currently selected event rule.
    pub selected_event_rule: Option<event_rules::EventRule>,
    /// The current list of cron workflows.
    pub cron_workflows: Vec<cron::CronWorkflow>,
    /// The state of the cron workflows list widget.
    pub cron_workflows_state: ListState,
    /// The currently selected cron workflow.
    pub selected_cron_workflow: Option<cron::CronWorkflow>,
    /// The index of the currently selected step within the detailed run view.
    pub selected_step_index: usize,
    /// The aggregated logs for the current view.
    pub run_logs: Vec<String>,
    /// The current scroll position within the logs view.
    pub log_scroll: usize,
    /// The current horizontal scroll position within the logs view.
    pub log_scroll_x: u16,
    /// Whether log view should automatically scroll to the bottom on new logs.
    pub log_auto_scroll: bool,
    /// The current scroll position within the overview pane.
    pub overview_scroll: usize,
    /// The currently focused UI pane.
    pub active_pane: Pane,
    /// The last encountered error message, if any.
    pub error: Option<String>,
    /// The timestamp of the last render cycle.
    pub render_time: Option<DateTime<Utc>>,
    /// The timestamp of the last successful data refresh.
    pub last_refresh_time: Option<DateTime<Utc>>,
    /// Channel for sending events back to the main application loop.
    pub status_tx: mpsc::Sender<AppEvent>,
    /// Handle for the background task watching run status.
    pub watcher_handle: Option<tokio::task::JoinHandle<()>>,
    pub force_select_run_id: Option<RunId>,
    /// Handle for the background task streaming logs.
    pub log_handle: Option<tokio::task::JoinHandle<()>>,
    /// Handle for the background task watching workflow details.
    pub workflow_handle: Option<tokio::task::JoinHandle<()>>,
    /// Whether the filter dialog is currently visible.
    pub filter_dialog_active: bool,
    /// The index of the currently focused input field in the filter dialog.
    pub filter_focus: usize,
    /// The text area inputs for the filter dialog.
    pub filter_inputs: Vec<TextArea<'a>>,
    /// The selected index for the status dropdown in the filter dialog.
    pub filter_status_index: usize,
    /// Whether the schedule git workflow dialog is active.
    pub schedule_git_dialog_active: bool,
    /// The index of the focused input in the schedule git dialog.
    pub schedule_git_focus: usize,
    /// The text area inputs for the schedule git dialog.
    pub schedule_git_inputs: Vec<TextArea<'a>>,
    /// Whether the storage backend dialog is active.
    pub connection_dialog_active: bool,
    /// The index of the focused input in the storage backend dialog.
    pub connection_focus: usize,
    /// The text area inputs for the storage backend dialog.
    pub connection_inputs: Vec<TextArea<'a>>,
    /// The index of the selected backend type.
    pub connection_type_index: usize,
    /// Whether the backend is the default SFS.
    pub connection_is_default: bool,
    /// The ID of the storage backend being edited, or None for creating a new one.
    pub connection_edit_id: Option<ConnectionId>,
    /// Whether the webhook dialog is active.
    pub webhook_dialog_active: bool,
    /// The index of the focused input in the webhook dialog.
    pub webhook_focus: usize,
    /// The text area inputs for the webhook dialog.
    pub webhook_inputs: Vec<TextArea<'a>>,
    /// The index of the selected webhook source type.
    pub webhook_source_type_index: usize,
    /// Whether the webhook is active.
    pub webhook_is_active: bool,
    /// The ID of the webhook being edited, or None for creating a new one.
    pub webhook_edit_id: Option<WebhookId>,
    /// Whether the event rule dialog is active.
    pub event_rule_dialog_active: bool,
    /// The index of the focused input in the event rule dialog.
    pub event_rule_focus: usize,
    /// The text area inputs for the event rule dialog.
    pub event_rule_inputs: Vec<TextArea<'a>>,
    /// Whether the event rule is active.
    pub event_rule_is_active: bool,
    /// The ID of the event rule being edited, or None for creating a new one.
    pub event_rule_edit_id: Option<RuleId>,
    /// Whether the cron workflow dialog is active.
    pub cron_dialog_active: bool,
    /// The index of the focused input in the cron dialog.
    pub cron_focus: usize,
    /// The text area inputs for the cron dialog.
    pub cron_inputs: Vec<TextArea<'a>>,
    /// Whether the cron workflow is active.
    pub cron_is_active: bool,
    /// The ID of the cron workflow being edited, or None for creating a new one.
    pub cron_edit_id: Option<CronWorkflowId>,
    /// Whether the approval dialog is active.
    pub approval_dialog_active: bool,
    /// Whether the delete run dialog is active.
    pub delete_run_dialog_active: bool,
    /// Text area for JSON inputs for step approval.
    pub approval_inputs: TextArea<'a>,
    /// Whether the file browser dialog is active.
    pub file_browser_active: bool,
    /// The state of the file explorer widget.
    pub file_explorer: tui_file_explorer::FileExplorer,
    /// Schema, DSL, and current inputs for pending schemaui run.
    pub pending_schema_ui: Option<schema_dialog::SchemaDialog<'a>>,
    /// The loaded DSL content for direct submission.
    pub direct_submit_dsl: Option<String>,
    /// Credentials loaded from deploy/dex/credentials.generated
    pub auto_login_credentials: Vec<(String, String)>,
    /// Index of the selected auto-login credential
    pub auto_login_index: usize,
    /// A cache of recently loaded full workflow run details.
    pub cached_runs: std::collections::HashMap<RunId, WorkflowRunFullDetail>,
    /// A set of step instance IDs for which full logs have been fetched.
    pub fetched_steps: std::collections::HashSet<StepInstanceId>,
    /// Marker to satisfy lifetime requirements for the struct.
    pub _marker: PhantomData<&'a ()>,
}

/// The available options for filtering by workflow run status.
pub const FILTER_STATUS_OPTIONS: &[&str] = &[
    "Any",
    "Queued",
    "Resolving",
    "Running",
    "Succeeded",
    "Failed",
    "Aborted",
];

/// The available storage backend types.
pub const BACKEND_TYPE_OPTIONS: &[&str] = &["S3", "Oci", "Jfrog", "Gcs", "Azure"];

/// The available webhook source types.
pub const WEBHOOK_SOURCE_TYPE_OPTIONS: &[&str] = &["github", "generic"];

/// API interaction methods.
pub mod api;
/// Dialog rendering and interaction logic.
pub mod dialogs;
/// Event handling logic for state transitions.
pub mod handlers;
/// User interface navigation and scrolling logic.
pub mod navigation;
/// Schema Dialog module.
pub mod schema_dialog;
/// Background watchers for real-time updates.
pub mod watch;

impl<'a> App<'a> {
    /// Creates a new instance of the TUI application state.
    pub fn new(
        url: String,
        query_url: String,
        token: Option<String>,
        status_tx: mpsc::Sender<AppEvent>,
    ) -> Self {
        let mut auto_login_credentials = Vec::new();
        if let Ok(content) = std::fs::read_to_string("deploy/dex/credentials.generated") {
            for line in content.lines() {
                if let Some((email, password)) = line.split_once(": ") {
                    if email.contains('@') {
                        auto_login_credentials
                            .push((email.trim().to_string(), password.trim().to_string()));
                    }
                }
            }
        }

        let state = if token.is_some() {
            AppState::LoggedIn
        } else {
            AppState::LoggedOut
        };

        Self {
            url,
            query_url,
            state,
            token,
            refresh_token: None,
            filter_owner: None,
            filter_name: None,
            filter_repo_url: None,
            filter_workflow_path: None,
            filter_created_after: None,
            filter_created_before: None,
            filter_status: None,
            runs: Vec::new(),
            runs_state: ListState::default(),
            selected_run: None,
            connections: Vec::new(),
            connections_state: ListState::default(),
            selected_connection: None,
            webhooks: Vec::new(),
            webhooks_state: ListState::default(),
            selected_webhook: None,
            event_rules: Vec::new(),
            event_rules_state: ListState::default(),
            selected_event_rule: None,
            cron_workflows: Vec::new(),
            cron_workflows_state: ListState::default(),
            selected_cron_workflow: None,
            selected_step_index: 0,
            run_logs: Vec::new(),
            log_scroll: 0,
            log_scroll_x: 0,
            log_auto_scroll: true,
            overview_scroll: 0,
            active_pane: Pane::RunsList,
            error: None,
            render_time: None,
            last_refresh_time: None,
            status_tx,
            watcher_handle: None,
            force_select_run_id: None,
            log_handle: None,
            workflow_handle: None,
            filter_dialog_active: false,
            filter_focus: 0,
            filter_inputs: Vec::new(),
            filter_status_index: 0,
            schedule_git_dialog_active: false,
            schedule_git_focus: 0,
            schedule_git_inputs: Vec::new(),
            connection_dialog_active: false,
            connection_focus: 0,
            connection_inputs: Vec::new(),
            connection_type_index: 0,
            connection_is_default: false,
            connection_edit_id: None,
            webhook_dialog_active: false,
            webhook_focus: 0,
            webhook_inputs: Vec::new(),
            webhook_source_type_index: 0,
            webhook_is_active: false,
            webhook_edit_id: None,
            event_rule_dialog_active: false,
            event_rule_focus: 0,
            event_rule_inputs: Vec::new(),
            event_rule_is_active: false,
            event_rule_edit_id: None,
            cron_dialog_active: false,
            cron_focus: 0,
            cron_inputs: Vec::new(),
            cron_is_active: false,
            cron_edit_id: None,
            approval_dialog_active: false,
            delete_run_dialog_active: false,
            approval_inputs: TextArea::default(),
            file_browser_active: false,
            pending_schema_ui: None,
            direct_submit_dsl: None,
            auto_login_credentials,
            auto_login_index: 0,
            cached_runs: HashMap::new(),
            fetched_steps: std::collections::HashSet::new(),
            file_explorer: tui_file_explorer::FileExplorer::new(
                std::env::current_dir().unwrap_or_default(),
                vec!["storm".to_string()],
            ),
            _marker: PhantomData,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tokio::sync::mpsc;

    #[test]
    fn test_app_new() {
        let (tx, _rx) = mpsc::channel(1);
        let app = App::new(
            "http://test".to_string(),
            "http://test:3001".to_string(),
            Some("token".to_string()),
            tx,
        );

        assert_eq!(app.url, "http://test");
        assert_eq!(app.query_url, "http://test:3001");
        assert_eq!(app.token, Some("token".to_string()));
        assert_eq!(app.state, AppState::LoggedIn);
        assert_eq!(app.active_pane, Pane::RunsList);
        assert!(app.run_logs.is_empty());
        assert_eq!(app.runs.len(), 0);
    }
}
