use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use uuid::Uuid;

pub type RunId = Uuid;
pub type StepInstanceId = Uuid;

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum RunStatus {
    Queued,
    Resolving,
    StartPending,
    Running,
    Succeeded,
    Failed,
    Aborted,
}

impl From<RunStatus> for String {
    fn from(s: RunStatus) -> Self {
        match s {
            RunStatus::Queued => "queued".to_string(),
            RunStatus::Resolving => "resolving".to_string(),
            RunStatus::StartPending => "start_pending".to_string(),
            RunStatus::Running => "running".to_string(),
            RunStatus::Succeeded => "succeeded".to_string(),
            RunStatus::Failed => "failed".to_string(),
            RunStatus::Aborted => "aborted".to_string(),
        }
    }
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum StepStatus {
    Pending,
    Initializing,
    UnpackingSfs,
    Running,
    PackingSfs,
    Succeeded,
    Failed,
    FailedIgnored,
    Skipped,
    WaitingForEvent,
    Aborted,
    LostZombie,
}

impl From<StepStatus> for String {
    fn from(s: StepStatus) -> Self {
        match s {
            StepStatus::Pending => "pending".to_string(),
            StepStatus::Initializing => "initializing".to_string(),
            StepStatus::UnpackingSfs => "unpacking_sfs".to_string(),
            StepStatus::Running => "running".to_string(),
            StepStatus::PackingSfs => "packing_sfs".to_string(),
            StepStatus::Succeeded => "succeeded".to_string(),
            StepStatus::Failed => "failed".to_string(),
            StepStatus::FailedIgnored => "failed_ignored".to_string(),
            StepStatus::Skipped => "skipped".to_string(),
            StepStatus::WaitingForEvent => "waiting_for_event".to_string(),
            StepStatus::Aborted => "aborted".to_string(),
            StepStatus::LostZombie => "lost_zombie".to_string(),
        }
    }
}

/// A summary of a workflow run, used for list views.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct WorkflowRunDetail {
    pub id: RunId,
    pub workflow_name: String,
    pub initiating_user: String,
    pub repo_url: String,
    pub workflow_path: String,
    pub git_ref: String,
    pub status: RunStatus,
    pub version: i32,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub started_resolving_at: Option<DateTime<Utc>>,
    pub started_at: Option<DateTime<Utc>>,
    pub finished_at: Option<DateTime<Utc>>,
    pub error: Option<String>,
    pub inputs: Value,
    pub secrets: Value,
}

/// Detailed information about a single step within a workflow run.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct StepDetail {
    /// The step instance data.
    pub instance: Value,
    /// The outputs produced by the step.
    pub outputs: Vec<Value>,
    /// The execution history of the step.
    pub history: Vec<Value>,
    /// The logs generated by the step.
    pub logs: Vec<String>,
}

/// Comprehensive details of a workflow run, including its steps and artifacts.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct WorkflowRunFullDetail {
    /// The summary details of the run.
    pub detail: WorkflowRunDetail,
    /// The detailed information for each step in the run.
    pub steps: Vec<StepDetail>,
    /// Artifacts generated during the run.
    pub artifacts: Vec<Value>,
    /// Test summaries generated during the run.
    pub test_summaries: Vec<Value>,
    /// Individual test cases executed during the run.
    pub test_cases: Vec<Value>,
}

pub type ConnectionId = Uuid;

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ConnectionType {
    S3,
    Oci,
    Jfrog,
    Gcs,
    Azure,
    Postgres,
    Mysql,
    HttpApi,
    Git,
}

impl std::fmt::Display for ConnectionType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let s = match self {
            ConnectionType::S3 => "S3",
            ConnectionType::Oci => "OCI Registry",
            ConnectionType::Jfrog => "JFrog",
            ConnectionType::Gcs => "GCS",
            ConnectionType::Azure => "Azure Blob",
            ConnectionType::Postgres => "PostgreSQL",
            ConnectionType::Mysql => "MySQL",
            ConnectionType::HttpApi => "HTTP API",
            ConnectionType::Git => "Git",
        };
        write!(f, "{}", s)
    }
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct Connection {
    pub id: ConnectionId,
    pub name: String,
    pub description: Option<String>,
    pub connection_type: ConnectionType,
    pub config: Value,
    pub encrypted_credentials: Option<String>,
    pub aws_assume_role_arn: Option<String>,
    pub is_default_sfs: bool,
    pub ca_cert: Option<String>,
    pub client_cert: Option<String>,
    pub client_key: Option<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

pub type WebhookId = Uuid;

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct WebhookConfig {
    pub id: WebhookId,
    pub name: String,
    pub description: Option<String>,
    pub source_type: String,
    pub secret_token: Option<String>,
    pub is_active: bool,
    pub ca_cert: Option<String>,
    pub client_cert: Option<String>,
    pub client_key: Option<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

pub type RuleId = Uuid;

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct EventRule {
    pub id: RuleId,
    pub name: String,
    pub description: Option<String>,
    pub webhook_id: Option<WebhookId>,
    pub event_type_pattern: String,
    pub condition_expr: Option<String>,
    pub workflow_name: String,
    pub repo_url: String,
    pub workflow_path: String,
    pub git_ref: String,
    pub input_mappings: Value,
    pub is_active: bool,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

pub type CronWorkflowId = Uuid;

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct CronWorkflow {
    pub id: CronWorkflowId,
    pub name: String,
    pub description: Option<String>,
    pub cronspec: String,
    pub workflow_name: String,
    pub repo_url: String,
    pub workflow_path: String,
    pub git_ref: String,
    pub inputs: Value,
    pub secret_token: String,
    pub is_active: bool,
    pub external_job_id: Option<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}
