use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use uuid::Uuid;

pub type RunId = Uuid;
pub type StepInstanceId = Uuid;

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum RunStatus {
    Queued,
    Resolving,
    StartPending,
    Running,
    Succeeded,
    Failed,
    Aborted,
}

impl From<RunStatus> for String {
    fn from(s: RunStatus) -> Self {
        match s {
            RunStatus::Queued => "queued".to_string(),
            RunStatus::Resolving => "resolving".to_string(),
            RunStatus::StartPending => "start_pending".to_string(),
            RunStatus::Running => "running".to_string(),
            RunStatus::Succeeded => "succeeded".to_string(),
            RunStatus::Failed => "failed".to_string(),
            RunStatus::Aborted => "aborted".to_string(),
        }
    }
}

#[derive(Debug, Serialize, Deserialize, Clone, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum StepStatus {
    Pending,
    UnpackingSfs,
    Running,
    PackingSfs,
    Succeeded,
    Failed,
    FailedIgnored,
    Skipped,
    WaitingForEvent,
    Aborted,
    LostZombie,
}

impl From<StepStatus> for String {
    fn from(s: StepStatus) -> Self {
        match s {
            StepStatus::Pending => "pending".to_string(),
            StepStatus::UnpackingSfs => "unpacking_sfs".to_string(),
            StepStatus::Running => "running".to_string(),
            StepStatus::PackingSfs => "packing_sfs".to_string(),
            StepStatus::Succeeded => "succeeded".to_string(),
            StepStatus::Failed => "failed".to_string(),
            StepStatus::FailedIgnored => "failed_ignored".to_string(),
            StepStatus::Skipped => "skipped".to_string(),
            StepStatus::WaitingForEvent => "waiting_for_event".to_string(),
            StepStatus::Aborted => "aborted".to_string(),
            StepStatus::LostZombie => "lost_zombie".to_string(),
        }
    }
}

/// A summary of a workflow run, used for list views.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct WorkflowRunDetail {
    /// Unique identifier for the run.
    pub id: RunId,
    /// Name of the workflow.
    pub workflow_name: String,
    /// The user who initiated the run.
    pub initiating_user: String,
    /// The current status of the run.
    pub status: RunStatus,
    /// The time the run was created.
    pub created_at: DateTime<Utc>,
    /// The time the run finished, if it has completed.
    pub finished_at: Option<DateTime<Utc>>,
}

/// Detailed information about a single step within a workflow run.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct StepDetail {
    /// The step instance data.
    pub instance: Value,
    /// The outputs produced by the step.
    pub outputs: Vec<Value>,
    /// The execution history of the step.
    pub history: Vec<Value>,
    /// The logs generated by the step.
    pub logs: Vec<String>,
}

/// Comprehensive details of a workflow run, including its steps and artifacts.
#[derive(Debug, Serialize, Deserialize, Clone, PartialEq)]
pub struct WorkflowRunFullDetail {
    /// The summary details of the run.
    pub detail: WorkflowRunDetail,
    /// The detailed information for each step in the run.
    pub steps: Vec<StepDetail>,
    /// Artifacts generated during the run.
    pub artifacts: Vec<Value>,
    /// Test summaries generated during the run.
    pub test_summaries: Vec<Value>,
    /// Individual test cases executed during the run.
    pub test_cases: Vec<Value>,
}
