[package]
publish = false
name = "stormchaser-dsl"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
stormchaser-model = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
hcl-rs = "0.18"
anyhow = { workspace = true }
thiserror = { workspace = true }
