[package]
name = "stormchaser-query"
version.workspace = true
edition.workspace = true
description = "Stormchaser query and hydration engine microservice"
repository.workspace = true
license.workspace = true

[[bin]]
name = "stormchaser-query"
path = "src/main.rs"

[dependencies]
stormchaser-model = { workspace = true }
stormchaser-engine = { path = "../stormchaser-engine" }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }
reqwest = { workspace = true }
jsonschema = { workspace = true }
hcl-rs = { workspace = true }
axum = { workspace = true }
tokio-stream = "0.1.18"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
stormchaser-api = { version = "1.4.0", path = "../stormchaser-api" }
stormchaser-tls = { version = "1.4.0", path = "../stormchaser-tls" }
stormchaser-opa = { version = "1.4.0", path = "../stormchaser-opa" }
async-nats.workspace = true
