apiVersion: apps/v1
kind: Deployment
metadata:
  name: dex
  namespace: stormchaser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dex
  template:
    metadata:
      labels:
        app: dex
    spec:
      initContainers:
      - name: inject-config
        image: alpine
        command:
        - sh
        - -c
        - "sed -e \"s|PASSWORD_HASH_ADMIN|$DEX_ADMIN_HASH|g\" -e \"s|PASSWORD_HASH_DEV|$DEX_DEV_HASH|g\" -e \"s|PASSWORD_HASH_OPS|$DEX_OPS_HASH|g\" -e \"s|PASSWORD_HASH_SEC|$DEX_SEC_HASH|g\" /config-template/config.yaml > /etc/dex/config.yaml"
        env:
        - name: DEX_ADMIN_HASH
          valueFrom:
            secretKeyRef:
              name: dex-admin-secret
              key: hash
        - name: DEX_DEV_HASH
          valueFrom:
            secretKeyRef:
              name: dex-dev-secret
              key: hash
        - name: DEX_OPS_HASH
          valueFrom:
            secretKeyRef:
              name: dex-ops-secret
              key: hash
        - name: DEX_SEC_HASH
          valueFrom:
            secretKeyRef:
              name: dex-sec-secret
              key: hash
        volumeMounts:
        - name: config-template
          mountPath: /config-template
        - name: config
          mountPath: /etc/dex
      containers:
      - command:
        - dex
        - serve
        - /etc/dex/config.yaml
        image: dexidp/dex:v2.41.1
        name: dex
        env:
        - name: STORMCHASER_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: stormchaser-db-secret
              key: password
        ports:
        - containerPort: 5556
          name: http
        volumeMounts:
        - mountPath: /etc/dex
          name: config
      volumes:
      - configMap:
          name: dex-config
        name: config-template
      - emptyDir: {}
        name: config
