name: CI

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

env:
  CARGO_TERM_COLOR: always
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  format:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - name: Patch ratatui-form
      run: ./scripts/patch-ratatui-form.sh
    - name: Run cargo fmt
      run: cargo fmt --all -- --check

  clippy:
    name: Run Clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Maximize Disk Space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - name: Patch ratatui-form
      run: ./scripts/patch-ratatui-form.sh
    - name: Generate Certificates
      run: ./scripts/generate-certs.sh
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
    - name: Run cargo clippy
      run: cargo clippy --workspace --all-targets --all-features -- -D warnings

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      SQLX_OFFLINE: "true"
      STORMCHASER_CERT_DIR: ./tests/certs
      API_RATE_LIMIT_BURST_SIZE: 1000
      API_RATE_LIMIT_PER_SECOND: 1000
    steps:
    - uses: actions/checkout@v4
    - name: Maximize Disk Space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - name: Patch ratatui-form
      run: ./scripts/patch-ratatui-form.sh
    - name: Cache dependencies
      uses: Swatinem/rust-cache@v2
    - name: Install sqlx-cli
      uses: taiki-e/install-action@v2
      with:
        tool: sqlx-cli
    - name: Start Infrastructure (NATS, Postgres)
      run: docker compose up -d --wait nats postgres
    - name: Generate Certificates
      run: ./scripts/generate-certs.sh
    - name: Run Database Migrations
      run: sqlx migrate run --database-url postgres://stormchaser:stormchaser@localhost:5432/stormchaser
    - name: Run Tests
      run: cargo test --workspace --all-features
